"use client";

import { useRef, useState } from "react";
import { motion, useInView } from "framer-motion";

const ESSAYS = [
  {
    title: "The Proving Mind",
    subtitle: "Why high achievers are the most spiritually displaced",
    date: "February 14, 2025",
    readTime: "12 min",
    tag: "Identity",
    accent: "#ff4d8d",
    excerpt:
      "There's a particular kind of exhaustion that high performers know well. It isn't the exhaustion of laziness or complacency. It's the exhaustion of someone who has been running at full capacity — and still feels like they're falling behind. This essay is about why that happens, and what it points toward.",
  },
  {
    title: "Source as Strategy",
    subtitle: "A rational case for operating from spirit",
    date: "January 28, 2025",
    readTime: "9 min",
    tag: "Philosophy",
    accent: "#7c7cdf",
    excerpt:
      "The objection I hear most often: 'This sounds spiritual, but I'm a rational person. I need things that actually work.' I understand the objection. I held it for years. But here's what I've found — operating from source isn't in tension with rationality. It is the rational move.",
  },
  {
    title: "Money as a Mirror",
    subtitle: "What your relationship with income reveals about your anchor",
    date: "January 12, 2025",
    readTime: "11 min",
    tag: "Abundance",
    accent: "#ff9a3c",
    excerpt:
      "Your relationship with money is a precise readout of your relationship with yourself. Not because money is spiritual or magical — but because the contraction that creates financial difficulty is the same contraction that creates every other form of limitation.",
  },
  {
    title: "Fear Is Structural",
    subtitle: "Why willpower doesn't fix what identity creates",
    date: "December 20, 2024",
    readTime: "8 min",
    tag: "Identity",
    accent: "#ff4d8d",
    excerpt:
      "Fear isn't a character flaw. It isn't a sign that you need more courage training or better morning routines. Fear is structural — it's generated by an identity that believes it must survive. Address the identity, and the fear loses its source.",
  },
  {
    title: "The Myth of Self-Authorship",
    subtitle: "On why you can't think your way to a new identity",
    date: "December 3, 2024",
    readTime: "14 min",
    tag: "Philosophy",
    accent: "#7c7cdf",
    excerpt:
      "Personal development culture is built on a seductive premise: that you can think your way into a new version of yourself. Read the right books. Install the right beliefs. Repeat affirmations until they take hold. This essay explores why that premise, while understandable, keeps people stuck at the level it's trying to solve.",
  },
  {
    title: "Exhaustion Is Diagnostic",
    subtitle: "What burnout is actually pointing at",
    date: "November 18, 2024",
    readTime: "7 min",
    tag: "Practice",
    accent: "#ff9a3c",
    excerpt:
      "Burnout is not a resource problem. You don't have burnout because you didn't sleep enough or take enough vacations. Burnout is what happens when you run the machinery of the small self at maximum capacity for too long. The exhaustion is the signal — if you know how to read it.",
  },
  {
    title: "The Difference Between Improving and Becoming",
    subtitle: "Why self-improvement keeps you small",
    date: "November 2, 2024",
    readTime: "10 min",
    tag: "Identity",
    accent: "#ff4d8d",
    excerpt:
      "Improvement says: I have flaws that need to be fixed. Becoming says: there's a fuller expression available that I haven't accessed yet. These sound similar. They produce completely different experiences — and completely different results.",
  },
  {
    title: "The Identity Beneath the Identity",
    subtitle: "Getting below the persona to what's actually running the show",
    date: "October 15, 2024",
    readTime: "13 min",
    tag: "Practice",
    accent: "#ff9a3c",
    excerpt:
      "Most identity work stays at the level of the persona — the story you tell about yourself. But beneath that persona is something older and deeper: the felt sense of what you are. Until that layer shifts, all the narrative work stays decorative.",
  },
];

const TAGS = ["All", "Identity", "Philosophy", "Abundance", "Practice"];

function EssayRow({
  essay,
  index,
}: {
  essay: (typeof ESSAYS)[0];
  index: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: "-40px" });
  const [expanded, setExpanded] = useState(false);

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 20 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.6, delay: index * 0.06 }}
      className="border-b border-zinc-100 last:border-0"
    >
      <div
        className="group py-8 cursor-pointer"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-start justify-between gap-6">
          <div className="flex-1">
            {/* Meta */}
            <div className="flex items-center gap-3 mb-3">
              <span
                className="text-[9px] uppercase tracking-[0.3em] font-semibold px-2.5 py-1 rounded-full"
                style={{
                  color: essay.accent,
                  background: `${essay.accent}14`,
                }}
              >
                {essay.tag}
              </span>
              <span className="text-[10px] text-zinc-400 tracking-wide">
                {essay.date}
              </span>
              <span className="text-[10px] text-zinc-400">·</span>
              <span className="text-[10px] text-zinc-400">{essay.readTime} read</span>
            </div>

            <h2 className="text-xl md:text-2xl font-semibold text-[#111] group-hover:text-[#ff4d8d] transition-colors leading-snug mb-1.5">
              {essay.title}
            </h2>
            <p className="text-zinc-500 text-sm">{essay.subtitle}</p>

            {/* Expandable excerpt */}
            <motion.div
              initial={false}
              animate={{ height: expanded ? "auto" : 0, opacity: expanded ? 1 : 0 }}
              transition={{ duration: 0.3 }}
              className="overflow-hidden"
            >
              <p className="text-zinc-600 text-sm leading-relaxed mt-4 max-w-2xl">
                {essay.excerpt}
              </p>
              <button className="mt-4 text-xs font-medium text-[#ff4d8d] hover:underline">
                Read full essay →
              </button>
            </motion.div>
          </div>

          <motion.span
            animate={{ rotate: expanded ? 45 : 0 }}
            transition={{ duration: 0.25 }}
            className="text-xl text-zinc-400 group-hover:text-[#ff4d8d] transition-colors flex-shrink-0 mt-1"
          >
            +
          </motion.span>
        </div>
      </div>
    </motion.div>
  );
}

export default function WritingPage() {
  const [activeTag, setActiveTag] = useState("All");

  const filtered = activeTag === "All"
    ? ESSAYS
    : ESSAYS.filter((e) => e.tag === activeTag);

  return (
    <main className="min-h-screen bg-white pt-28 pb-32">
      <div className="max-w-4xl mx-auto px-6 md:px-10">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          className="mb-16"
        >
          <p className="text-[10px] uppercase tracking-[0.35em] text-zinc-400 mb-5">
            The Writing
          </p>
          <h1 className="text-5xl md:text-6xl font-semibold text-[#111] leading-[1.02] tracking-tight mb-6">
            Long-form thinking.<br />
            <span className="text-zinc-400">No shortcuts.</span>
          </h1>
          <p className="text-zinc-500 text-lg leading-relaxed max-w-xl">
            Essays on identity, spirit, money, and what actually shifts when you change your foundation. Written to think — not to perform.
          </p>
        </motion.div>

        {/* Filter tags */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="flex flex-wrap gap-2 mb-14 pb-8 border-b border-zinc-100"
        >
          {TAGS.map((tag) => (
            <button
              key={tag}
              onClick={() => setActiveTag(tag)}
              className={`text-xs px-4 py-2 rounded-full border transition-all ${
                activeTag === tag
                  ? "bg-[#111] text-white border-[#111]"
                  : "border-zinc-200 text-zinc-500 hover:border-zinc-400 hover:text-zinc-700"
              }`}
            >
              {tag}
            </button>
          ))}
        </motion.div>

        {/* Essay list */}
        <div>
          {filtered.map((essay, i) => (
            <EssayRow key={essay.title} essay={essay} index={i} />
          ))}
        </div>

        {/* Newsletter CTA */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="mt-24 p-10 rounded-2xl bg-[#0d0d0d] text-center"
        >
          <p className="text-[10px] uppercase tracking-[0.35em] text-zinc-600 mb-4">
            Don&apos;t miss new essays
          </p>
          <h3 className="text-2xl font-semibold text-white mb-3">
            Subscribe to the thinking.
          </h3>
          <p className="text-zinc-500 text-sm mb-7 max-w-sm mx-auto">
            New essays arrive in your inbox. No noise, no filler — just the thinking.
          </p>
          <div className="flex gap-3 max-w-sm mx-auto">
            <input
              type="email"
              placeholder="your@email.com"
              className="flex-1 bg-[#1a1a1a] border border-zinc-800 rounded-lg px-4 py-3 text-sm text-white placeholder:text-zinc-600 focus:outline-none focus:border-[#ff4d8d] transition-colors"
            />
            <button className="bg-[#ff4d8d] text-white text-sm px-5 py-3 rounded-lg hover:bg-[#e0336d] transition-colors font-medium">
              Subscribe
            </button>
          </div>
        </motion.div>
      </div>
    </main>
  );
}
